[package]
name = "tool-derive"
version = "0.1.0"
authors = ["piaoliu <441594700@qq.com>"]
edition = "2018"

[lib]
name = "tool_derive"
proc-macro = true

[dependencies]
proc-macro2 = "^1.0.0"
quote = "^1.0.0"
syn = "^1.0.0"
